/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "OrderStatus".
 */
export type OrderStatus = ('processing' | 'completed' | 'cancelled' | 'refunded') | null;
/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    vendors: Vendor;
    'member-levels': MemberLevel;
    'point-transactions': PointTransaction;
    wishlist: Wishlist;
    'restock-requests': RestockRequest;
    promotions: Promotion;
    pages: Page;
    categories: Category;
    media: Media;
    adBanners: AdBanner;
    'scraper-platforms': ScraperPlatform;
    'scraping-jobs': ScrapingJob;
    'scraped-products': ScrapedProduct;
    forms: Form;
    'form-submissions': FormSubmission;
    addresses: Address;
    variants: Variant;
    variantTypes: VariantType;
    variantOptions: VariantOption;
    products: Product;
    carts: Cart;
    orders: Order;
    transactions: Transaction;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    users: {
      pointTransactions: 'point-transactions';
      orders: 'orders';
      cart: 'carts';
      addresses: 'addresses';
    };
    variantTypes: {
      options: 'variantOptions';
    };
    products: {
      variants: 'variants';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    vendors: VendorsSelect<false> | VendorsSelect<true>;
    'member-levels': MemberLevelsSelect<false> | MemberLevelsSelect<true>;
    'point-transactions': PointTransactionsSelect<false> | PointTransactionsSelect<true>;
    wishlist: WishlistSelect<false> | WishlistSelect<true>;
    'restock-requests': RestockRequestsSelect<false> | RestockRequestsSelect<true>;
    promotions: PromotionsSelect<false> | PromotionsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    adBanners: AdBannersSelect<false> | AdBannersSelect<true>;
    'scraper-platforms': ScraperPlatformsSelect<false> | ScraperPlatformsSelect<true>;
    'scraping-jobs': ScrapingJobsSelect<false> | ScrapingJobsSelect<true>;
    'scraped-products': ScrapedProductsSelect<false> | ScrapedProductsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    addresses: AddressesSelect<false> | AddressesSelect<true>;
    variants: VariantsSelect<false> | VariantsSelect<true>;
    variantTypes: VariantTypesSelect<false> | VariantTypesSelect<true>;
    variantOptions: VariantOptionsSelect<false> | VariantOptionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    carts: CartsSelect<false> | CartsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    transactions: TransactionsSelect<false> | TransactionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('zh-TW' | 'en') | ('zh-TW' | 'en')[];
  globals: {
    header: Header;
    footer: Footer;
    siteSettings: SiteSetting;
    trackingScripts: TrackingScript;
    'scraper-settings': ScraperSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    trackingScripts: TrackingScriptsSelect<false> | TrackingScriptsSelect<true>;
    'scraper-settings': ScraperSettingsSelect<false> | ScraperSettingsSelect<true>;
  };
  locale: 'zh-TW' | 'en';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
  /**
   * Generated by the Payload Ecommerce plugin
   */
  ecommerce: {
    collections: {
      addresses: Address;
      carts: Cart;
      customers?: User;
      orders: Order;
      products: Product;
      transactions: Transaction;
      variantOptions: VariantOption;
      variants: Variant;
      variantTypes: VariantType;
    };
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  roles?: ('super-admin' | 'admin' | 'vendor' | 'customer')[] | null;
  /**
   * 此用戶所屬的商家帳號
   */
  vendor?: (string | null) | Vendor;
  /**
   * 系統自動生成的 13 位會員編號
   */
  memberNumber?: string | null;
  phone?: string | null;
  /**
   * 自動由 LINE 綁定流程填入
   */
  lineUserId?: string | null;
  memberLevel?: ('bronze' | 'silver' | 'gold' | 'vip') | null;
  totalSpent?: number | null;
  /**
   * 自動由點數交易計算
   */
  points?: number | null;
  pointTransactions?: {
    docs?: (string | PointTransaction)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  orders?: {
    docs?: (string | Order)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  cart?: {
    docs?: (string | Cart)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  addresses?: {
    docs?: (string | Address)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors".
 */
export interface Vendor {
  id: string;
  name: string;
  /**
   * 用於 URL 路徑，例如: /vendor/your-slug
   */
  slug: string;
  description?: string | null;
  logo?: (string | null) | Media;
  status?: ('pending' | 'active' | 'suspended') | null;
  /**
   * 商家的錢包餘額（訂單結算後自動增加）
   */
  walletBalance?: number | null;
  /**
   * 平台從每筆訂單抽取的比例
   */
  commissionRate?: number | null;
  settings?: {
    autoAcceptOrders?: boolean | null;
    notificationEmail?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * 會員點數增減紀錄
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "point-transactions".
 */
export interface PointTransaction {
  id: string;
  /**
   * 點數所屬的會員
   */
  customer: string | User;
  type: 'earn' | 'redeem' | 'manual-add' | 'manual-deduct' | 'expired' | 'bonus' | 'refund';
  /**
   * 正數為增加，負數為扣減
   */
  amount: number;
  /**
   * 系統自動計算
   */
  balanceAfter?: number | null;
  description?: string | null;
  /**
   * 如果是消費獲得或退貨扣回，關聯到對應訂單
   */
  relatedOrder?: (string | null) | Order;
  /**
   * 此筆點數的有效期限
   */
  expiresAt?: string | null;
  /**
   * 手動調整時的操作人員
   */
  operator?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  items?:
    | {
        product?: (string | null) | Product;
        variant?: (string | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  shippingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  customer?: (string | null) | User;
  customerEmail?: string | null;
  transactions?: (string | Transaction)[] | null;
  status?: OrderStatus;
  amount?: number | null;
  currency?: ('TWD' | 'JPY' | 'USD') | null;
  /**
   * 從外部平台匯入的原始訂單編號
   */
  externalOrderId?: string | null;
  /**
   * 外部平台的客戶 Email，用於後續對接
   */
  externalCustomerEmail?: string | null;
  importedFrom?: ('easystore' | 'shopify' | 'other' | 'manual') | null;
  importedAt?: string | null;
  /**
   * 從外部平台匯入的商品快照（JSON），用於後續對接
   */
  externalItems?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: string;
  title: string;
  /**
   * 此商品所屬的商家
   */
  vendor: string | Vendor;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  gallery?:
    | {
        image: string | Media;
        variantOption?: (string | null) | VariantOption;
        id?: string | null;
      }[]
    | null;
  layout?: (CallToActionBlock | ContentBlock | MediaBlock)[] | null;
  inventory?: number | null;
  enableVariants?: boolean | null;
  variantTypes?: (string | VariantType)[] | null;
  variants?: {
    docs?: (string | Variant)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  priceInTWDEnabled?: boolean | null;
  priceInTWD?: number | null;
  priceInJPYEnabled?: boolean | null;
  priceInJPY?: number | null;
  priceInUSDEnabled?: boolean | null;
  priceInUSD?: number | null;
  relatedProducts?: (string | Product)[] | null;
  /**
   * 商品資料來源
   */
  externalSource?: ('beams' | 'zozo' | 'freaks' | 'easystore' | 'manual') | null;
  /**
   * 來源平台的商品編號
   */
  externalId?: string | null;
  /**
   * 商品在來源平台的原始連結
   */
  externalUrl?: string | null;
  /**
   * 爬蟲最後更新時間
   */
  lastSyncedAt?: string | null;
  syncStatus?: ('syncing' | 'synced' | 'failed' | 'na') | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  categories?: (string | Category)[] | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions".
 */
export interface VariantOption {
  id: string;
  _variantOptions_options_order?: string | null;
  variantType: string | VariantType;
  label: string;
  /**
   * should be defaulted or dynamic based on label
   */
  value: string;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes".
 */
export interface VariantType {
  id: string;
  label: string;
  name: string;
  options?: {
    docs?: (string | VariantOption)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  publishedOn?: string | null;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?: {
              relationTo: 'pages';
              value: string | Page;
            } | null;
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (string | null) | Media;
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | CarouselBlock
    | ThreeItemGridBlock
    | BannerBlock
    | FormBlock
    | ScrapbookHeroBlock
    | ScrapbookPromoBadgeBlock
    | ScrapbookIconsNavBlock
    | {
        title: string;
        subtitle?: string | null;
        /**
         * 自動模式會依據銷售數據計算排名
         */
        mode?: ('auto' | 'manual') | null;
        period?: ('7days' | '30days' | '90days' | 'alltime') | null;
        /**
         * 建議 5 或 10
         */
        itemCount?: number | null;
        /**
         * 留空則顯示全站排名
         */
        filterCategory?: (string | null) | Category;
        /**
         * 依序選擇要顯示的商品
         */
        products?: (string | Product)[] | null;
        pinnedProduct?: (string | null) | Product;
        pinnedLabel?: string | null;
        showRankNumber?: boolean | null;
        showPrice?: boolean | null;
        cardStyle?: ('scrapbook' | 'minimal' | 'magazine') | null;
        viewAllLink?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'scrapbookRanking';
      }
    | {
        title?: string | null;
        items?:
          | {
              title: string;
              description: string;
              /**
               * 如有優惠碼可在此填寫
               */
              code?: string | null;
              link?: string | null;
              color?: ('pink' | 'mint' | 'yellow' | 'lavender') | null;
              id?: string | null;
            }[]
          | null;
        viewAllLink?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'scrapbookNews';
      }
    | {
        title: string;
        subtitle?: string | null;
        /**
         * 選擇要展示的商品（建議 4-6 個）
         */
        products?: (string | Product)[] | null;
        viewAllLink?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'scrapbookCheckList';
      }
    | {
        /**
         * 可使用 emoji 增加視覺效果
         */
        text: string;
        speed?: ('slow' | 'normal' | 'fast') | null;
        direction?: ('left' | 'right') | null;
        texture?: ('kraft' | 'tape' | 'solid') | null;
        backgroundColor?: string | null;
        textColor?: string | null;
        fontSize?: ('sm' | 'md' | 'lg' | 'xl') | null;
        /**
         * 增加重複次數可讓跑馬燈更連續
         */
        repeatCount?: number | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'marquee';
      }
    | {
        title?: string | null;
        subtitle?: string | null;
        filterMode?: ('category' | 'manual' | 'latest' | 'bestselling') | null;
        limit?: number | null;
        categories?: (string | Category)[] | null;
        products?: (string | Product)[] | null;
        layout?: ('grid' | 'masonry' | 'carousel') | null;
        columns?: ('2' | '3' | '4' | '5') | null;
        showPrice?: boolean | null;
        showQuickView?: boolean | null;
        cardStyle?: ('scrapbook' | 'minimal' | 'bordered') | null;
        viewAllLink?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'productGrid';
      }
    | {
        title?: string | null;
        items?:
          | {
              image: string | Media;
              /**
               * 建議 -5 ~ 5 度
               */
              rotation?: number | null;
              size?: ('small' | 'medium' | 'large') | null;
              link?: string | null;
              caption?: string | null;
              id?: string | null;
            }[]
          | null;
        stickers?:
          | {
              text: string;
              style?: ('handwritten' | 'tape' | 'postit' | 'circle') | null;
              color?: ('pink' | 'mint' | 'yellow' | 'lavender' | 'kraft') | null;
              rotation?: number | null;
              id?: string | null;
            }[]
          | null;
        layout?: ('scattered' | 'grid' | 'stacked') | null;
        backgroundColor?: string | null;
        showTapeCorners?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'collage';
      }
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'products' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'products';
        value: string | Product;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  /**
   * 留空為全站分類
   */
  vendor?: (string | null) | Vendor;
  parent?: (string | null) | Category;
  description?: string | null;
  icon?: (string | null) | Media;
  /**
   * 數字越小越前面
   */
  sortOrder?: number | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock".
 */
export interface CarouselBlock {
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'products' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'products';
        value: string | Product;
      }[]
    | null;
  /**
   * This field is auto-populated after-read
   */
  populatedDocs?:
    | {
        relationTo: 'products';
        value: string | Product;
      }[]
    | null;
  /**
   * This field is auto-populated after-read
   */
  populatedDocsTotal?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'carousel';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeItemGridBlock".
 */
export interface ThreeItemGridBlock {
  products?: (string | Product)[] | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'threeItemGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: string | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ScrapbookHeroBlock".
 */
export interface ScrapbookHeroBlock {
  title: string;
  subtitle?: string | null;
  ctaText?: string | null;
  ctaLink?: string | null;
  backgroundImage?: (string | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'scrapbookHero';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ScrapbookPromoBadgeBlock".
 */
export interface ScrapbookPromoBadgeBlock {
  badges?:
    | {
        label: string;
        href?: string | null;
        color?: ('orange' | 'green' | 'red' | 'pink') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'scrapbookPromoBadge';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ScrapbookIconsNavBlock".
 */
export interface ScrapbookIconsNavBlock {
  items?:
    | {
        label: string;
        href?: string | null;
        iconType?: ('shop' | 'coordinate' | 'info' | 'coupon' | 'search' | 'user') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'scrapbookIconsNav';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants".
 */
export interface Variant {
  id: string;
  /**
   * Used for administrative purposes, not shown to customers. This is populated by default.
   */
  title?: string | null;
  product: string | Product;
  options: (string | VariantOption)[];
  inventory?: number | null;
  priceInTWDEnabled?: boolean | null;
  priceInTWD?: number | null;
  priceInJPYEnabled?: boolean | null;
  priceInJPY?: number | null;
  priceInUSDEnabled?: boolean | null;
  priceInUSD?: number | null;
  /**
   * 商品變體唯一識別碼（格式: FS-{hash}-{colorCode}-{size}）
   */
  sku?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions".
 */
export interface Transaction {
  id: string;
  items?:
    | {
        product?: (string | null) | Product;
        variant?: (string | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  paymentMethod?: 'stripe' | null;
  stripe?: {
    customerID?: string | null;
    paymentIntentID?: string | null;
  };
  billingAddress?: {
    title?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    company?: string | null;
    addressLine1?: string | null;
    addressLine2?: string | null;
    city?: string | null;
    state?: string | null;
    postalCode?: string | null;
    country?: string | null;
    phone?: string | null;
  };
  status: 'pending' | 'succeeded' | 'failed' | 'cancelled' | 'expired' | 'refunded';
  customer?: (string | null) | User;
  customerEmail?: string | null;
  order?: (string | null) | Order;
  cart?: (string | null) | Cart;
  amount?: number | null;
  currency?: ('TWD' | 'JPY' | 'USD') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts".
 */
export interface Cart {
  id: string;
  items?:
    | {
        product?: (string | null) | Product;
        variant?: (string | null) | Variant;
        quantity: number;
        id?: string | null;
      }[]
    | null;
  secret?: string | null;
  customer?: (string | null) | User;
  purchasedAt?: string | null;
  status?: ('active' | 'purchased' | 'abandoned') | null;
  subtotal?: number | null;
  currency?: ('TWD' | 'JPY' | 'USD') | null;
  /**
   * 購物車被系統標記為遺棄的時間
   */
  abandonedAt?: string | null;
  /**
   * 此購物車是否被標記為遺棄
   */
  isAbandoned?: boolean | null;
  /**
   * 最後一次發送提醒的時間
   */
  reminderSentAt?: string | null;
  /**
   * 已發送提醒的次數
   */
  reminderCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses".
 */
export interface Address {
  id: string;
  customer?: (string | null) | User;
  title?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  company?: string | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  state?: string | null;
  postalCode?: string | null;
  country:
    | 'US'
    | 'GB'
    | 'CA'
    | 'AU'
    | 'AT'
    | 'BE'
    | 'BR'
    | 'BG'
    | 'CY'
    | 'CZ'
    | 'DK'
    | 'EE'
    | 'FI'
    | 'FR'
    | 'DE'
    | 'GR'
    | 'HK'
    | 'HU'
    | 'IN'
    | 'IE'
    | 'IT'
    | 'JP'
    | 'LV'
    | 'LT'
    | 'LU'
    | 'MY'
    | 'MT'
    | 'MX'
    | 'NL'
    | 'NZ'
    | 'NO'
    | 'PL'
    | 'PT'
    | 'RO'
    | 'SG'
    | 'SK'
    | 'SI'
    | 'ES'
    | 'SE'
    | 'CH';
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 定義會員等級規則與福利
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-levels".
 */
export interface MemberLevel {
  id: string;
  name: string;
  /**
   * 用於系統識別，不可重複
   */
  code: string;
  /**
   * 數字越大等級越高
   */
  order?: number | null;
  /**
   * 建議使用透明背景的 PNG 或 SVG
   */
  icon?: (string | null) | Media;
  /**
   * 用於 UI 顯示的主題色（Hex 格式）
   */
  color?: string | null;
  /**
   * 達到此金額即可升級
   */
  minSpent?: number | null;
  /**
   * 達到此訂單數即可升級（與消費金額取其一）
   */
  minOrders?: number | null;
  /**
   * 判斷升級的邏輯
   */
  upgradeLogic?: ('or' | 'and' | 'spent-only' | 'orders-only') | null;
  /**
   * 例如：5 表示打 95 折
   */
  discountPercent?: number | null;
  /**
   * 正價商品的點數倍率（例如：2 = 雙倍點數）。折扣商品不受此倍率影響。
   */
  pointsMultiplier?: number | null;
  /**
   * 消費滿此金額免運費
   */
  freeShippingThreshold?: number | null;
  /**
   * 生日月份自動發放的購物金
   */
  birthdayBonus?: number | null;
  /**
   * 顯示給用戶看的等級介紹
   */
  description?: string | null;
  /**
   * 新用戶自動設為此等級（應只有一個等級勾選）
   */
  isDefault?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wishlist".
 */
export interface Wishlist {
  id: string;
  /**
   * 收藏此商品的顧客
   */
  customer: string | User;
  /**
   * 收藏的商品
   */
  product: string | Product;
  variant?: {
    color?: string | null;
    size?: string | null;
    sku?: string | null;
    /**
     * 加入願望清單時的價格，用於判斷降價
     */
    priceAtAdd?: number | null;
  };
  /**
   * 當此商品降價時發送通知
   */
  notifyOnPriceDrop?: boolean | null;
  /**
   * 避免重複通知相同價格
   */
  lastNotifiedPrice?: number | null;
  lastNotifiedAt?: string | null;
  addedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 客戶希望補貨的商品清單
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "restock-requests".
 */
export interface RestockRequest {
  id: string;
  customer: string | User;
  product: string | Product;
  variant?: {
    color?: string | null;
    size?: string | null;
    sku?: string | null;
  };
  /**
   * 通知狀態
   */
  status: 'pending' | 'notified' | 'cancelled';
  /**
   * 使用的通知管道（自動選擇或手動指定）
   */
  notificationChannel?: ('line' | 'email') | null;
  requestedAt?: string | null;
  /**
   * 發送通知的時間
   */
  notifiedAt?: string | null;
  /**
   * 內部備註（顧客不可見）
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions".
 */
export interface Promotion {
  id: string;
  name: string;
  description?: string | null;
  type: 'percentage' | 'fixed' | 'buyXgetY' | 'freeShipping';
  /**
   * 百分比折扣填 10 代表 10% off；固定金額填實際金額
   */
  value?: number | null;
  buyXgetY?: {
    buyQuantity?: number | null;
    getQuantity?: number | null;
  };
  /**
   * 留空表示無最低消費限制
   */
  minPurchase?: number | null;
  /**
   * 留空表示適用全部商品
   */
  applicableProducts?: (string | Product)[] | null;
  /**
   * 留空表示適用全部分類
   */
  applicableCategories?: (string | Category)[] | null;
  /**
   * 留空表示不限會員等級
   */
  applicableUserLevels?: ('bronze' | 'silver' | 'gold' | 'vip')[] | null;
  stackable?: boolean | null;
  /**
   * 數字越大越優先計算
   */
  priority?: number | null;
  startDate: string;
  endDate: string;
  status?: ('draft' | 'active' | 'expired') | null;
  /**
   * 留空表示不限次數
   */
  usageLimit?: number | null;
  usedCount?: number | null;
  /**
   * 留空表示全站促銷
   */
  vendor?: (string | null) | Vendor;
  /**
   * 留空表示自動適用，填入則需輸入代碼
   */
  code?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adBanners".
 */
export interface AdBanner {
  id: string;
  /**
   * 內部識別用，不會顯示在前台
   */
  name: string;
  status?: ('draft' | 'scheduled' | 'active' | 'ended') | null;
  /**
   * 選擇廣告顯示的位置
   */
  placement:
    | 'home-hero'
    | 'home-middle'
    | 'home-footer'
    | 'shop-top'
    | 'shop-sidebar'
    | 'product-below'
    | 'cart-sidebar'
    | 'global-floating';
  image: string | Media;
  /**
   * 如未上傳，將自動縮放桌面版圖片
   */
  mobileImage?: (string | null) | Media;
  /**
   * 用於 SEO 與無障礙
   */
  altText: string;
  link?: string | null;
  linkTarget?: ('_self' | '_blank') | null;
  /**
   * 留空表示立即開始
   */
  startDate?: string | null;
  /**
   * 留空表示永久顯示
   */
  endDate?: string | null;
  /**
   * 數字越大優先順序越高，相同位置的廣告會按此排序
   */
  priority?: number | null;
  trackClicks?: boolean | null;
  /**
   * 系統自動統計
   */
  clickCount?: number | null;
  /**
   * 系統自動統計
   */
  impressionCount?: number | null;
  utmSource?: string | null;
  utmMedium?: string | null;
  utmCampaign?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 管理各網站的爬蟲配置
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scraper-platforms".
 */
export interface ScraperPlatform {
  id: string;
  name: string;
  /**
   * 用於 API 識別，請使用小寫英文和連字號
   */
  slug: string;
  baseUrl: string;
  isActive?: boolean | null;
  /**
   * 顯示在平台列表中的小圖示
   */
  icon?: (string | null) | Media;
  urlPatterns: {
    /**
     * 正則表達式，匹配列表頁 URL
     */
    listing: string;
    /**
     * 正則表達式，匹配商品頁 URL，可用括號捕獲商品 ID
     */
    product: string;
  };
  listingSelectors: {
    /**
     * 包含單一商品的容器元素
     */
    productCard: string;
    /**
     * 指向商品詳情頁的連結
     */
    productLink: string;
    /**
     * 屬性名稱或選擇器，用於提取商品 ID
     */
    productId?: string | null;
    thumbnail?: string | null;
    title?: string | null;
    brand?: string | null;
    price?: string | null;
    originalPrice?: string | null;
    nextPage?: string | null;
    /**
     * URL 中的頁碼參數
     */
    pageParam?: string | null;
    totalCount?: string | null;
  };
  /**
   * 啟用後可提取商品詳情、變體、尺寸表等完整資訊
   */
  supportDeepScrape?: boolean | null;
  productSelectors?: {
    title?: string | null;
    brand?: string | null;
    price?: string | null;
    description?: string | null;
    images?: string | null;
    variants?: string | null;
    variantColor?: string | null;
    variantSize?: string | null;
    stockStatus?: string | null;
    sizeChart?: string | null;
    materials?: string | null;
  };
  settings?: {
    /**
     * 翻頁之間的等待時間
     */
    pageDelay?: number | null;
    /**
     * 每個請求之間的等待時間
     */
    requestDelay?: number | null;
    maxRetries?: number | null;
    /**
     * 此平台需要登入才能爬取
     */
    requiresLogin?: boolean | null;
    userAgent?: string | null;
  };
  pricing?: {
    useGlobalPricing?: boolean | null;
    currency?: ('JPY' | 'USD' | 'TWD') | null;
    /**
     * 不使用全局設定時，可自訂此平台的定價層級
     */
    customPricingTiers?:
      | {
          name?: string | null;
          minPrice?: number | null;
          maxPrice?: number | null;
          exchangeRate?: number | null;
          taxMultiplier?: number | null;
          handlingFee?: number | null;
          shippingFee?: number | null;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * JSON 格式的自定義函數配置，用於特殊情況的資料提取。請謹慎使用。
   */
  customExtractors?: string | null;
  totalProductsScraped?: number | null;
  lastUsedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 管理爬蟲任務的執行
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scraping-jobs".
 */
export interface ScrapingJob {
  id: string;
  platform: string | ScraperPlatform;
  /**
   * 深層：完整資料；淺層：僅價格庫存
   */
  type: 'deep' | 'shallow';
  /**
   * 列表頁或單一商品頁的 URL
   */
  sourceUrl: string;
  /**
   * 自動偵測
   */
  urlType?: ('listing' | 'product') | null;
  status?: ('pending' | 'running' | 'paused' | 'completed' | 'failed' | 'cancelled') | null;
  progress?: {
    currentPage?: number | null;
    totalPages?: number | null;
    productsFound?: number | null;
    productsProcessed?: number | null;
    productsImported?: number | null;
    productsSkipped?: number | null;
    errors?: number | null;
    /**
     * 正在處理的頁面 URL
     */
    currentUrl?: string | null;
  };
  config?: {
    /**
     * 0 = 無限制
     */
    maxPages?: number | null;
    /**
     * 0 = 無限制
     */
    maxProducts?: number | null;
    /**
     * 從第幾頁開始
     */
    startPage?: number | null;
    /**
     * 跳過已匯入的商品
     */
    excludeExisting?: boolean | null;
    /**
     * 爬取完成後自動執行匯入
     */
    autoImport?: boolean | null;
    /**
     * 將圖片下載到 Media
     */
    downloadImages?: boolean | null;
  };
  startedAt?: string | null;
  completedAt?: string | null;
  /**
   * 任務執行的總時長
   */
  duration?: number | null;
  logs?:
    | {
        timestamp?: string | null;
        level?: ('info' | 'warn' | 'error' | 'debug') | null;
        message?: string | null;
        data?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 任務失敗時的錯誤詳情
   */
  errorMessage?: string | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * 爬取後的商品暫存區，可編輯後再匯入
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scraped-products".
 */
export interface ScrapedProduct {
  id: string;
  job: string | ScrapingJob;
  platform: string | ScraperPlatform;
  /**
   * 來源平台的商品 ID
   */
  externalId: string;
  externalUrl: string;
  originalTitle?: string | null;
  /**
   * 可手動編輯
   */
  translatedTitle?: string | null;
  brand?: string | null;
  category?: string | null;
  /**
   * 原始描述（日文）
   */
  description?: string | null;
  /**
   * 翻譯後的描述（可編輯）
   */
  translatedDescription?: string | null;
  originalPrice?: number | null;
  /**
   * 如有折扣
   */
  salePrice?: number | null;
  /**
   * 根據定價規則計算
   */
  calculatedPrice?: number | null;
  /**
   * 價格計算的詳細步驟
   */
  pricingDetails?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  thumbnailUrl?: string | null;
  imageUrls?:
    | {
        url?: string | null;
        /**
         * 此圖片對應的顏色
         */
        colorName?: string | null;
        /**
         * Base64 編碼圖片（由 Extension 下載）
         */
        base64?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * 包含顏色、尺寸、庫存等資訊
   */
  variants?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * 尺寸對照表資料
   */
  sizeChart?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  materials?: string | null;
  translationStatus?: ('pending' | 'translated' | 'review' | 'manual') | null;
  /**
   * 無法翻譯的原因或注意事項
   */
  translationNotes?: string | null;
  importStatus?: ('pending' | 'review' | 'imported' | 'skipped' | 'failed') | null;
  importedProduct?: (string | null) | Product;
  scrapedAt?: string | null;
  importedAt?: string | null;
  importError?: string | null;
  /**
   * 完整的原始 JSON 資料，用於除錯
   */
  rawData?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'vendors';
        value: string | Vendor;
      } | null)
    | ({
        relationTo: 'member-levels';
        value: string | MemberLevel;
      } | null)
    | ({
        relationTo: 'point-transactions';
        value: string | PointTransaction;
      } | null)
    | ({
        relationTo: 'wishlist';
        value: string | Wishlist;
      } | null)
    | ({
        relationTo: 'restock-requests';
        value: string | RestockRequest;
      } | null)
    | ({
        relationTo: 'promotions';
        value: string | Promotion;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'adBanners';
        value: string | AdBanner;
      } | null)
    | ({
        relationTo: 'scraper-platforms';
        value: string | ScraperPlatform;
      } | null)
    | ({
        relationTo: 'scraping-jobs';
        value: string | ScrapingJob;
      } | null)
    | ({
        relationTo: 'scraped-products';
        value: string | ScrapedProduct;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'addresses';
        value: string | Address;
      } | null)
    | ({
        relationTo: 'variants';
        value: string | Variant;
      } | null)
    | ({
        relationTo: 'variantTypes';
        value: string | VariantType;
      } | null)
    | ({
        relationTo: 'variantOptions';
        value: string | VariantOption;
      } | null)
    | ({
        relationTo: 'products';
        value: string | Product;
      } | null)
    | ({
        relationTo: 'carts';
        value: string | Cart;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null)
    | ({
        relationTo: 'transactions';
        value: string | Transaction;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  vendor?: T;
  memberNumber?: T;
  phone?: T;
  lineUserId?: T;
  memberLevel?: T;
  totalSpent?: T;
  points?: T;
  pointTransactions?: T;
  orders?: T;
  cart?: T;
  addresses?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vendors_select".
 */
export interface VendorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  logo?: T;
  status?: T;
  walletBalance?: T;
  commissionRate?: T;
  settings?:
    | T
    | {
        autoAcceptOrders?: T;
        notificationEmail?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "member-levels_select".
 */
export interface MemberLevelsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  order?: T;
  icon?: T;
  color?: T;
  minSpent?: T;
  minOrders?: T;
  upgradeLogic?: T;
  discountPercent?: T;
  pointsMultiplier?: T;
  freeShippingThreshold?: T;
  birthdayBonus?: T;
  description?: T;
  isDefault?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "point-transactions_select".
 */
export interface PointTransactionsSelect<T extends boolean = true> {
  customer?: T;
  type?: T;
  amount?: T;
  balanceAfter?: T;
  description?: T;
  relatedOrder?: T;
  expiresAt?: T;
  operator?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "wishlist_select".
 */
export interface WishlistSelect<T extends boolean = true> {
  customer?: T;
  product?: T;
  variant?:
    | T
    | {
        color?: T;
        size?: T;
        sku?: T;
        priceAtAdd?: T;
      };
  notifyOnPriceDrop?: T;
  lastNotifiedPrice?: T;
  lastNotifiedAt?: T;
  addedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "restock-requests_select".
 */
export interface RestockRequestsSelect<T extends boolean = true> {
  customer?: T;
  product?: T;
  variant?:
    | T
    | {
        color?: T;
        size?: T;
        sku?: T;
      };
  status?: T;
  notificationChannel?: T;
  requestedAt?: T;
  notifiedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions_select".
 */
export interface PromotionsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  type?: T;
  value?: T;
  buyXgetY?:
    | T
    | {
        buyQuantity?: T;
        getQuantity?: T;
      };
  minPurchase?: T;
  applicableProducts?: T;
  applicableCategories?: T;
  applicableUserLevels?: T;
  stackable?: T;
  priority?: T;
  startDate?: T;
  endDate?: T;
  status?: T;
  usageLimit?: T;
  usedCount?: T;
  vendor?: T;
  code?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  publishedOn?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        carousel?: T | CarouselBlockSelect<T>;
        threeItemGrid?: T | ThreeItemGridBlockSelect<T>;
        banner?: T | BannerBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        scrapbookHero?: T | ScrapbookHeroBlockSelect<T>;
        scrapbookPromoBadge?: T | ScrapbookPromoBadgeBlockSelect<T>;
        scrapbookIconsNav?: T | ScrapbookIconsNavBlockSelect<T>;
        scrapbookRanking?:
          | T
          | {
              title?: T;
              subtitle?: T;
              mode?: T;
              period?: T;
              itemCount?: T;
              filterCategory?: T;
              products?: T;
              pinnedProduct?: T;
              pinnedLabel?: T;
              showRankNumber?: T;
              showPrice?: T;
              cardStyle?: T;
              viewAllLink?: T;
              id?: T;
              blockName?: T;
            };
        scrapbookNews?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    code?: T;
                    link?: T;
                    color?: T;
                    id?: T;
                  };
              viewAllLink?: T;
              id?: T;
              blockName?: T;
            };
        scrapbookCheckList?:
          | T
          | {
              title?: T;
              subtitle?: T;
              products?: T;
              viewAllLink?: T;
              id?: T;
              blockName?: T;
            };
        marquee?:
          | T
          | {
              text?: T;
              speed?: T;
              direction?: T;
              texture?: T;
              backgroundColor?: T;
              textColor?: T;
              fontSize?: T;
              repeatCount?: T;
              id?: T;
              blockName?: T;
            };
        productGrid?:
          | T
          | {
              title?: T;
              subtitle?: T;
              filterMode?: T;
              limit?: T;
              categories?: T;
              products?: T;
              layout?: T;
              columns?: T;
              showPrice?: T;
              showQuickView?: T;
              cardStyle?: T;
              viewAllLink?: T;
              id?: T;
              blockName?: T;
            };
        collage?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    image?: T;
                    rotation?: T;
                    size?: T;
                    link?: T;
                    caption?: T;
                    id?: T;
                  };
              stickers?:
                | T
                | {
                    text?: T;
                    style?: T;
                    color?: T;
                    rotation?: T;
                    id?: T;
                  };
              layout?: T;
              backgroundColor?: T;
              showTapeCorners?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CarouselBlock_select".
 */
export interface CarouselBlockSelect<T extends boolean = true> {
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  populatedDocs?: T;
  populatedDocsTotal?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ThreeItemGridBlock_select".
 */
export interface ThreeItemGridBlockSelect<T extends boolean = true> {
  products?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock_select".
 */
export interface BannerBlockSelect<T extends boolean = true> {
  style?: T;
  content?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ScrapbookHeroBlock_select".
 */
export interface ScrapbookHeroBlockSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  ctaText?: T;
  ctaLink?: T;
  backgroundImage?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ScrapbookPromoBadgeBlock_select".
 */
export interface ScrapbookPromoBadgeBlockSelect<T extends boolean = true> {
  badges?:
    | T
    | {
        label?: T;
        href?: T;
        color?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ScrapbookIconsNavBlock_select".
 */
export interface ScrapbookIconsNavBlockSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        href?: T;
        iconType?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  vendor?: T;
  parent?: T;
  description?: T;
  icon?: T;
  sortOrder?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adBanners_select".
 */
export interface AdBannersSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  placement?: T;
  image?: T;
  mobileImage?: T;
  altText?: T;
  link?: T;
  linkTarget?: T;
  startDate?: T;
  endDate?: T;
  priority?: T;
  trackClicks?: T;
  clickCount?: T;
  impressionCount?: T;
  utmSource?: T;
  utmMedium?: T;
  utmCampaign?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scraper-platforms_select".
 */
export interface ScraperPlatformsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  baseUrl?: T;
  isActive?: T;
  icon?: T;
  urlPatterns?:
    | T
    | {
        listing?: T;
        product?: T;
      };
  listingSelectors?:
    | T
    | {
        productCard?: T;
        productLink?: T;
        productId?: T;
        thumbnail?: T;
        title?: T;
        brand?: T;
        price?: T;
        originalPrice?: T;
        nextPage?: T;
        pageParam?: T;
        totalCount?: T;
      };
  supportDeepScrape?: T;
  productSelectors?:
    | T
    | {
        title?: T;
        brand?: T;
        price?: T;
        description?: T;
        images?: T;
        variants?: T;
        variantColor?: T;
        variantSize?: T;
        stockStatus?: T;
        sizeChart?: T;
        materials?: T;
      };
  settings?:
    | T
    | {
        pageDelay?: T;
        requestDelay?: T;
        maxRetries?: T;
        requiresLogin?: T;
        userAgent?: T;
      };
  pricing?:
    | T
    | {
        useGlobalPricing?: T;
        currency?: T;
        customPricingTiers?:
          | T
          | {
              name?: T;
              minPrice?: T;
              maxPrice?: T;
              exchangeRate?: T;
              taxMultiplier?: T;
              handlingFee?: T;
              shippingFee?: T;
              id?: T;
            };
      };
  customExtractors?: T;
  totalProductsScraped?: T;
  lastUsedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scraping-jobs_select".
 */
export interface ScrapingJobsSelect<T extends boolean = true> {
  platform?: T;
  type?: T;
  sourceUrl?: T;
  urlType?: T;
  status?: T;
  progress?:
    | T
    | {
        currentPage?: T;
        totalPages?: T;
        productsFound?: T;
        productsProcessed?: T;
        productsImported?: T;
        productsSkipped?: T;
        errors?: T;
        currentUrl?: T;
      };
  config?:
    | T
    | {
        maxPages?: T;
        maxProducts?: T;
        startPage?: T;
        excludeExisting?: T;
        autoImport?: T;
        downloadImages?: T;
      };
  startedAt?: T;
  completedAt?: T;
  duration?: T;
  logs?:
    | T
    | {
        timestamp?: T;
        level?: T;
        message?: T;
        data?: T;
        id?: T;
      };
  errorMessage?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scraped-products_select".
 */
export interface ScrapedProductsSelect<T extends boolean = true> {
  job?: T;
  platform?: T;
  externalId?: T;
  externalUrl?: T;
  originalTitle?: T;
  translatedTitle?: T;
  brand?: T;
  category?: T;
  description?: T;
  translatedDescription?: T;
  originalPrice?: T;
  salePrice?: T;
  calculatedPrice?: T;
  pricingDetails?: T;
  thumbnailUrl?: T;
  imageUrls?:
    | T
    | {
        url?: T;
        colorName?: T;
        base64?: T;
        id?: T;
      };
  variants?: T;
  sizeChart?: T;
  materials?: T;
  translationStatus?: T;
  translationNotes?: T;
  importStatus?: T;
  importedProduct?: T;
  scrapedAt?: T;
  importedAt?: T;
  importError?: T;
  rawData?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "addresses_select".
 */
export interface AddressesSelect<T extends boolean = true> {
  customer?: T;
  title?: T;
  firstName?: T;
  lastName?: T;
  company?: T;
  addressLine1?: T;
  addressLine2?: T;
  city?: T;
  state?: T;
  postalCode?: T;
  country?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variants_select".
 */
export interface VariantsSelect<T extends boolean = true> {
  title?: T;
  product?: T;
  options?: T;
  inventory?: T;
  priceInTWDEnabled?: T;
  priceInTWD?: T;
  priceInJPYEnabled?: T;
  priceInJPY?: T;
  priceInUSDEnabled?: T;
  priceInUSD?: T;
  sku?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantTypes_select".
 */
export interface VariantTypesSelect<T extends boolean = true> {
  label?: T;
  name?: T;
  options?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "variantOptions_select".
 */
export interface VariantOptionsSelect<T extends boolean = true> {
  _variantOptions_options_order?: T;
  variantType?: T;
  label?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  title?: T;
  vendor?: T;
  description?: T;
  gallery?:
    | T
    | {
        image?: T;
        variantOption?: T;
        id?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
      };
  inventory?: T;
  enableVariants?: T;
  variantTypes?: T;
  variants?: T;
  priceInTWDEnabled?: T;
  priceInTWD?: T;
  priceInJPYEnabled?: T;
  priceInJPY?: T;
  priceInUSDEnabled?: T;
  priceInUSD?: T;
  relatedProducts?: T;
  externalSource?: T;
  externalId?: T;
  externalUrl?: T;
  lastSyncedAt?: T;
  syncStatus?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  categories?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carts_select".
 */
export interface CartsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  secret?: T;
  customer?: T;
  purchasedAt?: T;
  status?: T;
  subtotal?: T;
  currency?: T;
  abandonedAt?: T;
  isAbandoned?: T;
  reminderSentAt?: T;
  reminderCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  shippingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  customer?: T;
  customerEmail?: T;
  transactions?: T;
  status?: T;
  amount?: T;
  currency?: T;
  externalOrderId?: T;
  externalCustomerEmail?: T;
  importedFrom?: T;
  importedAt?: T;
  externalItems?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "transactions_select".
 */
export interface TransactionsSelect<T extends boolean = true> {
  items?:
    | T
    | {
        product?: T;
        variant?: T;
        quantity?: T;
        id?: T;
      };
  paymentMethod?: T;
  stripe?:
    | T
    | {
        customerID?: T;
        paymentIntentID?: T;
      };
  billingAddress?:
    | T
    | {
        title?: T;
        firstName?: T;
        lastName?: T;
        company?: T;
        addressLine1?: T;
        addressLine2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        phone?: T;
      };
  status?: T;
  customer?: T;
  customerEmail?: T;
  order?: T;
  cart?: T;
  amount?: T;
  currency?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navItems?:
    | {
        label: string;
        style?: ('default' | 'highlight' | 'button') | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
        };
        hasSubMenu?: boolean | null;
        subMenu?:
          | {
              type?: ('link' | 'promo') | null;
              linkLabel?: string | null;
              link?: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?: {
                  relationTo: 'pages';
                  value: string | Page;
                } | null;
                url?: string | null;
              };
              promoImage?: (string | null) | Media;
              promoLink?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  showSearch?: boolean | null;
  showCart?: boolean | null;
  showAccount?: boolean | null;
  mobileMenuStyle?: ('slide' | 'fullscreen') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  /**
   * 最多 4 個欄位，每個欄位可包含多個連結
   */
  columns?:
    | {
        title: string;
        links?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?: {
                  relationTo: 'pages';
                  value: string | Page;
                } | null;
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        platform?: ('facebook' | 'instagram' | 'twitter' | 'line' | 'youtube' | 'tiktok') | null;
        url: string;
        id?: string | null;
      }[]
    | null;
  showPaymentIcons?: boolean | null;
  paymentMethods?: ('visa' | 'mastercard' | 'jcb' | 'applepay' | 'googlepay' | 'linepay' | 'atm' | 'cod')[] | null;
  /**
   * 使用 {year} 會自動替換為當前年份
   */
  copyrightText?: string | null;
  legalLinks?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * 相容舊版資料使用，建議改用上方的「連結區塊」
   */
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: string | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: string;
  /**
   * 建議使用 SVG 或透明背景 PNG
   */
  mainLogo?: (string | null) | Media;
  /**
   * 建議尺寸 32x32 或 64x64
   */
  favicon?: (string | null) | Media;
  siteName: string;
  brandColors?: {
    /**
     * 品牌主色 (如 EasyStore 風格)
     */
    primary?: string | null;
    accent?: string | null;
    /**
     * 復古牛皮紙風格
     */
    background?: string | null;
    text?: string | null;
    textMuted?: string | null;
    border?: string | null;
  };
  typography?: {
    /**
     * 用於標題和重要文字
     */
    headingFont?:
      | ('Noto Sans TC' | 'Noto Serif TC' | 'Inter' | 'Playfair Display' | 'Montserrat' | 'Poppins' | 'system-ui')
      | null;
    /**
     * 用於段落和一般文字
     */
    bodyFont?: ('Noto Sans TC' | 'Noto Serif TC' | 'Inter' | 'Open Sans' | 'Roboto' | 'Lato' | 'system-ui') | null;
    baseFontSize?: number | null;
    lineHeight?: number | null;
  };
  seo?: {
    defaultTitle?: string | null;
    defaultDescription?: string | null;
    /**
     * 社群分享預覽圖 (建議 1200x630)
     */
    ogImage?: (string | null) | Media;
  };
  currency: {
    /**
     * 商品價格顯示的幣別
     */
    defaultCurrency: 'TWD' | 'USD' | 'JPY' | 'CNY' | 'HKD';
    /**
     * 顯示在價格前的符號
     */
    currencySymbol?: string | null;
    /**
     * EasyStore 商品的原始幣別
     */
    easyStoreCurrency?: ('TWD' | 'USD' | 'JPY' | 'CNY' | 'HKD') | null;
    /**
     * 匯入時是否自動轉換幣別
     */
    enableCurrencyConversion?: boolean | null;
    /**
     * 設定其他幣別轉換為預設幣別的匯率
     */
    exchangeRates?:
      | {
          fromCurrency: 'USD' | 'JPY' | 'CNY' | 'HKD' | 'TWD';
          /**
           * 1 單位 = ? 預設幣別
           */
          rate: number;
          lastUpdated?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * 記錄匯率來源或注意事項
     */
    exchangeRateNote?: string | null;
  };
  cartSettings?: {
    freeShippingEnabled?: boolean | null;
    /**
     * 消費滿此金額享免運
     */
    freeShippingThreshold?: number | null;
    /**
     * 未達免運門檻時的運費
     */
    defaultShippingFee?: number | null;
    /**
     * 使用 {amount} 代表剩餘金額
     */
    freeShippingMessage?: string | null;
    freeShippingAchievedMessage?: string | null;
    emptyCartTitle?: string | null;
    emptyCartButtonText?: string | null;
    showRecentlyViewed?: boolean | null;
    recentlyViewedTitle?: string | null;
  };
  announcementBar?: {
    enabled?: boolean | null;
    text?: string | null;
    link?: string | null;
    backgroundColor?: string | null;
    textColor?: string | null;
  };
  loyaltyPoints?: {
    /**
     * 關閉後，系統將不再累積或折抵點數
     */
    enabled?: boolean | null;
    /**
     * 每消費多少元
     */
    pointsPerAmount?: number | null;
    /**
     * 可獲得幾點（正價商品）
     */
    pointsEarned?: number | null;
    /**
     * 例如：1 點 = 1 元
     */
    pointValue?: number | null;
    /**
     * 累積滿多少點才能開始折抵
     */
    minPointsToRedeem?: number | null;
    /**
     * 已打折商品的點數回饋規則（不受會員等級倍率加成）
     */
    discountProductRule?: {
      /**
       * 折扣商品的固定點數回饋比例
       */
      fixedPercentage?: number | null;
      /**
       * 例如：3 倍活動期間，折扣商品為 3%
       */
      applyCampaignMultiplier?: boolean | null;
    };
    campaign?: {
      enabled?: boolean | null;
      /**
       * 例如：2 = 雙倍點數
       */
      multiplier?: number | null;
      name?: string | null;
      startDate?: string | null;
      endDate?: string | null;
    };
    advanced?: {
      /**
       * 0 = 永不過期
       */
      pointsExpireDays?: number | null;
      /**
       * 單筆訂單最多可折抵多少 % 金額
       */
      maxRedeemPercentage?: number | null;
      /**
       * 勾選後，運費不會累積點數
       */
      excludeShipping?: boolean | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 管理第三方追蹤碼，修改後前台會自動套用
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trackingScripts".
 */
export interface TrackingScript {
  id: string;
  gtmEnabled?: boolean | null;
  /**
   * 格式: GTM-XXXXXXX
   */
  gtmId?: string | null;
  metaPixelEnabled?: boolean | null;
  /**
   * 15-16 位數字 ID
   */
  metaPixelId?: string | null;
  /**
   * 用於伺服器端事件傳送 (CAPI)
   */
  metaAccessToken?: string | null;
  ga4Enabled?: boolean | null;
  /**
   * 格式: G-XXXXXXXXXX
   */
  ga4MeasurementId?: string | null;
  hotjarEnabled?: boolean | null;
  hotjarId?: string | null;
  /**
   * 注入至 <head> 標籤內
   */
  customHeadScript?: string | null;
  /**
   * 注入至 </body> 前
   */
  customBodyScript?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scraper-settings".
 */
export interface ScraperSetting {
  id: string;
  pricing?: {
    /**
     * 1 日圓 = ? 台幣
     */
    defaultExchangeRate?: number | null;
    roundingRule?: ('ceil10' | 'ceil100' | 'round10' | 'none') | null;
    /**
     * 根據原價範圍套用不同的計算公式
     */
    tiers?:
      | {
          name: string;
          minPrice: number;
          /**
           * 留空 = 無上限
           */
          maxPrice?: number | null;
          taxMultiplier?: number | null;
          handlingFee?: number | null;
          shippingFee?: number | null;
          id?: string | null;
        }[]
      | null;
    /**
     * 價格計算公式參考
     */
    pricingFormula?: string | null;
  };
  translation?: {
    enabled?: boolean | null;
    fallbackMode?: ('keep' | 'review') | null;
    /**
     * 可用變數: {brand}, {feature}, {category}, {color}
     */
    template?: string | null;
    /**
     * 日文分類 → 中文分類
     */
    categoryMappings?:
      | {
          japanese: string;
          chinese: string;
          id?: string | null;
        }[]
      | null;
    /**
     * 日文顏色 → 中文顏色
     */
    colorMappings?:
      | {
          japanese: string;
          chinese: string;
          id?: string | null;
        }[]
      | null;
    /**
     * 日文尺寸項目 → 中文
     */
    sizeMappings?:
      | {
          japanese: string;
          chinese: string;
          id?: string | null;
        }[]
      | null;
  };
  import?: {
    /**
     * 匯入商品時的預設商家
     */
    defaultVendor?: (string | null) | Vendor;
    /**
     * 將圖片從來源網站下載到本地
     */
    downloadImages?: boolean | null;
    /**
     * 根據爬取的顏色/尺寸建立變體
     */
    createVariants?: boolean | null;
    /**
     * 匯入後自動設為已發布狀態
     */
    autoPublish?: boolean | null;
    defaultCategory?: (string | null) | Category;
    /**
     * 標記商品來源平台
     */
    externalSource?: ('freaks' | 'beams' | 'zozo' | 'other') | null;
    /**
     * 同時下載圖片的數量（過高可能被封鎖）
     */
    maxConcurrentDownloads?: number | null;
  };
  extension?: {
    enabled?: boolean | null;
    /**
     * Extension 驗證用的 API Key
     */
    apiKey?: string | null;
    /**
     * Extension 連線的 WebSocket URL
     */
    wsEndpoint?: string | null;
    /**
     * Extension 回報存活狀態的間隔
     */
    heartbeatInterval?: number | null;
    /**
     * 超過此時間無心跳視為斷線
     */
    connectionTimeout?: number | null;
    /**
     * 用於提示用戶更新
     */
    extensionVersion?: string | null;
    /**
     * 用戶下載 Extension 的連結
     */
    extensionDownloadUrl?: string | null;
  };
  status?: {
    totalJobsRun?: number | null;
    totalProductsScraped?: number | null;
    totalProductsImported?: number | null;
    lastJobAt?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        style?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
            };
        hasSubMenu?: T;
        subMenu?:
          | T
          | {
              type?: T;
              linkLabel?: T;
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                  };
              promoImage?: T;
              promoLink?: T;
              id?: T;
            };
        id?: T;
      };
  showSearch?: T;
  showCart?: T;
  showAccount?: T;
  mobileMenuStyle?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  showPaymentIcons?: T;
  paymentMethods?: T;
  copyrightText?: T;
  legalLinks?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  mainLogo?: T;
  favicon?: T;
  siteName?: T;
  brandColors?:
    | T
    | {
        primary?: T;
        accent?: T;
        background?: T;
        text?: T;
        textMuted?: T;
        border?: T;
      };
  typography?:
    | T
    | {
        headingFont?: T;
        bodyFont?: T;
        baseFontSize?: T;
        lineHeight?: T;
      };
  seo?:
    | T
    | {
        defaultTitle?: T;
        defaultDescription?: T;
        ogImage?: T;
      };
  currency?:
    | T
    | {
        defaultCurrency?: T;
        currencySymbol?: T;
        easyStoreCurrency?: T;
        enableCurrencyConversion?: T;
        exchangeRates?:
          | T
          | {
              fromCurrency?: T;
              rate?: T;
              lastUpdated?: T;
              id?: T;
            };
        exchangeRateNote?: T;
      };
  cartSettings?:
    | T
    | {
        freeShippingEnabled?: T;
        freeShippingThreshold?: T;
        defaultShippingFee?: T;
        freeShippingMessage?: T;
        freeShippingAchievedMessage?: T;
        emptyCartTitle?: T;
        emptyCartButtonText?: T;
        showRecentlyViewed?: T;
        recentlyViewedTitle?: T;
      };
  announcementBar?:
    | T
    | {
        enabled?: T;
        text?: T;
        link?: T;
        backgroundColor?: T;
        textColor?: T;
      };
  loyaltyPoints?:
    | T
    | {
        enabled?: T;
        pointsPerAmount?: T;
        pointsEarned?: T;
        pointValue?: T;
        minPointsToRedeem?: T;
        discountProductRule?:
          | T
          | {
              fixedPercentage?: T;
              applyCampaignMultiplier?: T;
            };
        campaign?:
          | T
          | {
              enabled?: T;
              multiplier?: T;
              name?: T;
              startDate?: T;
              endDate?: T;
            };
        advanced?:
          | T
          | {
              pointsExpireDays?: T;
              maxRedeemPercentage?: T;
              excludeShipping?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trackingScripts_select".
 */
export interface TrackingScriptsSelect<T extends boolean = true> {
  gtmEnabled?: T;
  gtmId?: T;
  metaPixelEnabled?: T;
  metaPixelId?: T;
  metaAccessToken?: T;
  ga4Enabled?: T;
  ga4MeasurementId?: T;
  hotjarEnabled?: T;
  hotjarId?: T;
  customHeadScript?: T;
  customBodyScript?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scraper-settings_select".
 */
export interface ScraperSettingsSelect<T extends boolean = true> {
  pricing?:
    | T
    | {
        defaultExchangeRate?: T;
        roundingRule?: T;
        tiers?:
          | T
          | {
              name?: T;
              minPrice?: T;
              maxPrice?: T;
              taxMultiplier?: T;
              handlingFee?: T;
              shippingFee?: T;
              id?: T;
            };
        pricingFormula?: T;
      };
  translation?:
    | T
    | {
        enabled?: T;
        fallbackMode?: T;
        template?: T;
        categoryMappings?:
          | T
          | {
              japanese?: T;
              chinese?: T;
              id?: T;
            };
        colorMappings?:
          | T
          | {
              japanese?: T;
              chinese?: T;
              id?: T;
            };
        sizeMappings?:
          | T
          | {
              japanese?: T;
              chinese?: T;
              id?: T;
            };
      };
  import?:
    | T
    | {
        defaultVendor?: T;
        downloadImages?: T;
        createVariants?: T;
        autoPublish?: T;
        defaultCategory?: T;
        externalSource?: T;
        maxConcurrentDownloads?: T;
      };
  extension?:
    | T
    | {
        enabled?: T;
        apiKey?: T;
        wsEndpoint?: T;
        heartbeatInterval?: T;
        connectionTimeout?: T;
        extensionVersion?: T;
        extensionDownloadUrl?: T;
      };
  status?:
    | T
    | {
        totalJobsRun?: T;
        totalProductsScraped?: T;
        totalProductsImported?: T;
        lastJobAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}